### ISSUE TITLE
Galaxy version outdated?

### ISSUE THREAD

**Issue by jfoliveira** [morgangraphics/ansible-role-nvm#19]
Hi,
Thanks for providing this NVM role to the community! It's pretty useful.

I just installed the version from Ansible Galaxy and noticed that the version there says **Last commit 6 months ago** whereas in this github repository there have been commits in the past 2 months:
https://galaxy.ansible.com/morgangraphics/ansible_role_nvm 

Perhaps might be a good idea to auto import on git push to master using TravisCI:
https://galaxy.ansible.com/docs/contributing/importing.html#import-roles-via-travis-ci

**Comment by morgangraphics** [comment]
This is part of the work I am doing with an idempotency branch I started a while back [here](https://github.com/morgangraphics/ansible-role-nvm/tree/feature/idempotency-linting-testing). Just picking this work up again as part of my TODO list. It's tied to the work in #18 as well

**Comment by jfoliveira** [comment]
Cloning the role from source definitely is not the best approach for me, as I want/need to reinstall roles from Galaxy reading dependencies from my `requirements.txt` file.

I have no experience with molecule and role testing but I'm willing to learn.

If you need help with setting up GitHub actions CI/CD to run tests automatically and even publish new role versions to Ansible Galaxy when the tests pass let me know and I can work on a PR and submit it so you can review and merge - if approved.

**Comment by morgangraphics** [comment]
This is still a work in progress as I've had address some other priorities before coming back to this. **It is on the list of things to do right now**. In the mean time I manually update the Ansible Galaxy version every time I made updates to this repo.

**Comment by morgangraphics** [comment]
I've made a few updates in this repo and Ansible Galaxy is up to date.
